#include "repo.h"

void create_tonomat(Repo &r){
    Produs p1("33", "Cafea", 10);
    Produs p2("44", "Ceai", 50);
    Produs p3("55", "Apa Plata", 5);
    Produs p4("66", "Apa Minerala", 100);
    Monezi m;
    m.add_moneda(500);
    m.add_moneda(500);
    m.add_moneda(500);
    m.add_moneda(500);
    m.add_moneda(500);
    m.add_moneda(500);
    m.add_moneda(500);
    m.add_moneda(500);
    m.add_moneda(500);
    m.add_moneda(500);
    m.add_moneda(200);
    m.add_moneda(200);
    m.add_moneda(200);
    m.add_moneda(200);
    m.add_moneda(200);
    m.add_moneda(200);
    m.add_moneda(200);
    m.add_moneda(200);
    m.add_moneda(100);
    m.add_moneda(100);
    m.add_moneda(100);
    m.add_moneda(100);
    m.add_moneda(100);
    m.add_moneda(100);
    m.add_moneda(100);
    m.add_moneda(100);
    m.add_moneda(100);
    m.add_moneda(100);
    m.add_moneda(50);
    m.add_moneda(50);
    m.add_moneda(50);
    m.add_moneda(50);
    m.add_moneda(50);
    m.add_moneda(20);
    m.add_moneda(20);
    m.add_moneda(20);
    m.add_moneda(20);
    m.add_moneda(20);
    m.add_moneda(50);
    m.add_moneda(50);
    m.add_moneda(50);
    m.add_moneda(50);
    m.add_moneda(50);
    m.add_moneda(20);
    m.add_moneda(20);
    m.add_moneda(20);
    m.add_moneda(20);
    m.add_moneda(20);
    m.add_moneda(10);
    m.add_moneda(10);
    m.add_moneda(10);
    m.add_moneda(10);
    m.add_moneda(10);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(5);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(1);
    m.add_moneda(1);
    r.add_produs(p1);
    r.add_produs(p2);
    r.add_produs(p3);
    r.add_produs(p4);
    r.add_monezi(m);
}

